config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :cares
  post 'care', to: 'welcome#care'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/care.rb
class Care < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cares_controller.rb
class CaresController < ApplicationController
  before_action :set_care, only: [:show, :edit, :update, :destroy]

  # GET /cares
  # GET /cares.json
  def index
    @cares = Care.all
  end

  # GET /cares/1
  # GET /cares/1.json
  def show
  end

  # GET /cares/new
  def new
    @care = Care.new
  end

  # GET /cares/1/edit
  def edit
  end

  # POST /cares
  # POST /cares.json
  def create
    @care = Care.new(care_params)
    respond_to do |format|
      if @care.save
        format.html { redirect_to @care, notice: 'Care was successfully created.' }
        format.json { render :show, status: :created, location: @care }
      else
        format.html { render :new }
        format.json { render json: @care.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cares/1
  # PATCH/PUT /cares/1.json
  def update
    respond_to do |format|
      if @care.update(care_params)
        format.html { redirect_to @care, notice: 'Care was successfully updated.' }
        format.json { render :show, status: :ok, location: @care }
      else
        format.html { render :edit }
        format.json { render json: @care.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cares/1
  # DELETE /cares/1.json
  def destroy
    @care.destroy
    respond_to do |format|
      format.html { redirect_to cares_url, notice: 'Care was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_care
      @care = Care.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def care_params
      params.require(:care).permit(:fed, :medicated, :fedAt, :medicatedAt)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :setMostRecentCare, :checkTimeAndReset

  def home
      @mostRecentCareFeedTime = @mostRecentCare.fedAt.in_time_zone('Eastern Time (US & Canada)')
      @fedStatus = @mostRecentCare.fed
      @mostRecentCareMedicateTime = @mostRecentCare.medicatedAt.in_time_zone('Eastern Time (US & Canada)')
      @medicatedStatus = @mostRecentCare.medicated
      @currentTimeObject
      if @currentTimeObject.strftime("%p") == 'PM'
        secondLastCare = Care.all[-2]
        if secondLastCare.created_at.strftime("%p") == 'AM' && secondLastCare.created_at.strftime("%m%d") == @currentTimeObject.strftime("%m%d")
          @morningCare = secondLastCare
        end
      end
  end

  def care
    if params[:fed]
      @mostRecentCare.update(fed: true, fedAt: @currentTimeObject)
      redirect_to root_path
    end
    if params[:medicated]
      @mostRecentCare.update(medicated: true, medicatedAt: @currentTimeObject)
      redirect_to root_path
    end
  end

  private

  def setMostRecentCare
    @mostRecentCare = Care.last
    if @mostRecentCare
      if @mostRecentCare.created_at.strftime("%p") == 'AM'
        @mostRecentCareTimeOfDay = "morning"
      else
        @mostRecentCareTimeOfDay = "evening"
      end
    end
  end

  def checkTimeAndReset
    @currentTimeObject = Time.now.in_time_zone('Eastern Time (US & Canada)')
    if @currentTimeObject.strftime("%p") == 'AM'
      @timeOfDay = "morning"
    else
      @timeOfDay = "evening"
    end
    checkCurrentCare
  end

  def checkCurrentCare
    # check if there are any cares
    if @mostRecentCare
      # check if most recent care created was today
      if @mostRecentCare.created_at.strftime("%m%d") == @currentTimeObject.strftime("%m%d")
        # checks if the current AM/PM matches the last care's AM/PM
        if @timeOfDay == @mostRecentCareTimeOfDay
          return
        else
          @mostRecentCare = Care.create(fed: false, medicated: false, fedAt: @currentTimeObject, medicatedAt: @currentTimeObject)
        end
      else
        @mostRecentCare = Care.create(fed: false, medicated: false, fedAt: @currentTimeObject, medicatedAt: @currentTimeObject)
      end
    else
      @mostRecentCare = Care.create(fed: false, medicated: false, fedAt: @currentTimeObject, medicatedAt: @currentTimeObject)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cares_helper.rb
module CaresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cares/_form.html.erb
<%= form_with(model: care, local: true) do |form| %>
  <% if care.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(care.errors.count, "error") %> prohibited this care from being saved:</h2>

      <ul>
      <% care.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fed %>
    <%= form.check_box :fed %>
    <%= form.hidden_field :fedAt, :value => Time.now%>
  </div>

  <div class="field">
    <%= form.label :medicated %>
    <%= form.check_box :medicated %>
    <%= form.hidden_field :medicatedAt, :value => Time.now %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cares/edit.html.erb
<h1>Editing Care</h1>

<%= render 'form', care: @care %>

<%= link_to 'Show', @care %> |
<%= link_to 'Back', cares_path %>

app/views/cares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cares</h1>

<table>
  <thead>
    <tr>
      <th>Fed</th>
      <th>Medicated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cares.each do |care| %>
      <tr>
        <td><%= care.fed %></td>
        <td><%= care.medicated %></td>
        <td><%= link_to 'Show', care %></td>
        <td><%= link_to 'Edit', edit_care_path(care) %></td>
        <td><%= link_to 'Destroy', care, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Care', new_care_path %>

app/views/cares/new.html.erb
<h1>New Care</h1>

<%= render 'form', care: @care %>

<%= link_to 'Back', cares_path %>

app/views/cares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fed:</strong>
  <%= @care.fed %>
  <%= @care.fedAt %>
</p>

<p>
  <strong>Medicated:</strong>
  <%= @care.medicated %>
  <%= @care.medicatedAt %>
</p>

<%= link_to 'Edit', edit_care_path(@care) %> |
<%= link_to 'Back', cares_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dog Feeder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="apple-touch-icon" href="dog.jpeg">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<div class="container">
<h1>Fed?</h1>
<% if @fedStatus %>
  At <%= @mostRecentCareFeedTime.strftime("%I:%M") %>
<% else %>
  Not yet
<% end %>
<% if @mostRecentCareFeedTime.strftime("%p") == "AM" %>
  this morning.
<% else %>
  this evening.
<% end %>
<% if !@fedStatus %>
<br>
<%= button_to "Feed", {action: "care", fed: true}, {class: 'button'}%>
<% end %>
<div class="historyText">
  <% if @morningCare %>
    <% if @morningCare.fedAt %>
      Was fed at <%= @morningCare.fedAt.strftime("%I:%M") %> this morning.
    <% end %>
  <% end %>
</div>

<% if @currentTimeObject.strftime("%p") == 'AM' %>
  <h1>Medicated?</h1>
  <% if @medicatedStatus %>
    At <%= @mostRecentCareMedicateTime.strftime("%I:%M") %>
  <% else %>
    Not yet
  <% end %>
  <% if @mostRecentCareMedicateTime.strftime("%p") == "AM" %>
    this morning.
  <% else %>
    this evening.
  <% end %>
  <% if !@medicatedStatus %>
  <br>
  <%= button_to "Medicate", {action: "care", medicated: true}, {class: 'button'}%>
  <% end %>
<% end %>
<div class="historyText">
  <% if @morningCare %>
    <% if @morningCare.medicatedAt %>
      Was medicated at <%= @morningCare.medicatedAt.strftime("%I:%M") %> this morning.
    <% end %>
  <% end %>
</div>
</div>